<?php
return [
    [
        'type' => 'Primi piatti',
        'name' => 'Fettuccine al Pesto Genovese',
        'ingredients' => 'Pancetta, Uovo, Parmigiano',
        'description' => 'è un grande classico della cucina ligure, un primo piatto saporito e profumato ed anche molto veloce da preparare!',
        'price' => '6,00',
        'image' => 'https://www.ilcuoreinpentola.it/wp-content/uploads/2010/03/pasta-al-pesto-alla-genovese.jpg',


    ],
    [
        'type' => 'Primi piatti',
        'name' => 'Spaghetti alla Carbonara',
        'ingredients' => 'Pancetta, Uovo, Parmigiano',
        'description' => 'La pasta alla carbonara è un piatto caratteristico del Lazio e più in particolare di Roma, preparato con ingredienti popolari e dal gusto intenso. I tipi di pasta tradizionalmente più usati sono gli spaghetti e i rigatoni.',
        'price' => '6,50',
        'image' => 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/recipe-image-legacy-id-1001491_11-2e0fa5c.jpg?resize=768,574',
    ],
    [
        'type' => 'Primi piatti',
        'name' => "Bucatini all'Amatriciana",
        'ingredients' => 'Sugo di pomodoro, Pancetta, Cipolla, Peperoncino, Pecorino',
        'description' => 'La pasta all’amatriciana (o matriciana) è un piatto tipico delle trattorie e osterie romane ma originario della cittadina di Amatrice, in provincia di Rieti. ',
        'price' => '7,00',
        'image' => 'https://media-assets.lacucinaitaliana.it/photos/620fbef3e7e73824639990a3/1:1/w_2560%2Cc_limit/bucatini-allamatriciana.jpg',
    ],
    [
        'type' => 'Primi piatti',
        'name' => 'Spaghetti Napoli',
        'ingredients' => 'Sugo di pomodoro, Parmigiano',
        'description' => 'Una ricetta della tradizione in stile Lilli e il Vagabondo: i classici spaghetti alla napoletana. Deliziosa con l’aggiunta di polpettine di carne.',
        'price' => '5,50',
        'image' => 'https://www.finedininglovers.com/sites/g/files/xknfdk626/files/styles/amp_metadata_content_image_min_696px_wide/public/Original_7582_spaghetti-napoli.jpg?itok=2dESbrQI',
    ],
    [
        'type' => 'Secondi piatti',
        'name' => 'Filetto di Pollo Panato',
        'ingredients' => 'Pollo',
        'description' => 'Petto di pollo accuratamente affettato e preparato con una panatura di uovo e pangrattato aromatizzato con spezie.',
        'price' => '7,00',
        'image' => 'https://primochef.it/wp-content/uploads/2020/06/SH_petto_di_pollo_impanato.jpg',
    ],

    [
        'type' => 'Secondi piatti',
        'name' => 'Scaloppina al Vino Bianco',
        'ingredients' => 'Scaloppine, Vino Bianco',
        'description' => 'Le scaloppine al vino bianco sono un secondo piatto tipico della cucina milanese.È un piatto molto apprezzato per la semplicità e la velocità di preparazione. Il gusto è delicato ma per ottenere un risultato eccellente occorre impiegare un vino bianco di grande qualità.',
        'price' => '8,00',
        'image' => 'https://cdn.ilclubdellericette.it/wp-content/uploads/2017/06/scaloppine-vino-bianco-790x500.jpg.webp',
    ],
    [
        'type' => 'Secondi piatti',
        'name' => 'Calamari Fritti',
        'ingredients' => 'Calamari',
        'description' => "calamari fritti (a volte detti anche calamari alla romana) s'intende un piatto a base di calamari o di totani, della cucina italiana, e di quelle di altre nazioni, come la spagnola, la greca, la turca e l'argentina.",
        'price' => '8,00',
        'image' => 'https://wips.plug.it/cips/buonissimo.org/cms/2012/06/calamari-fritti-6.jpg',
    ],
    [
        'type' => 'Secondi piatti',
        'name' => 'Pesce Spada alla griglia',
        'ingredients' => 'pesce spada',
        'description' => "Il pesce spada alla piastra, o pesce spada alla griglia, è un secondo piatto leggero e saporito, perfetto per un fresco pranzo estivo da accompagnare a un'insalata colorata o a un contorno di verdure di stagione.",
        'price' => '9,00',
        'image' => 'https://primochef.it/wp-content/uploads/2019/04/SH_pesce_spada_grigliato-1200x800.jpg',
    ],
    [
        'type' => 'Kebab',
        'name' => 'Panino Kebab',
        'ingredients' => 'Carne, Insalata, Cipolla, Salse, Piccante',
        'description' => ' consiste in un grande cilindro di carne speziata che viene cotta su un grande spiedo verticale. La carne che andrà a farcire panini o piadine o in un piatto viene tagliata a scaglie e condita con salse e verdure a piacere.',
        'price' => '4,00',
        'image' => 'https://cdn.ilclubdellericette.it/wp-content/uploads/2019/06/kebab-fatto-in-casa-790x500.jpg',
    ],
    [
        'type' => 'Kebab',
        'name' => 'Menu Panino Kebab',
        'ingredients' => 'Carne, Insalata, Cipolla, Salse, Piccante + Patatine a parte',
        'description' => 'Panino kebab accompagnato da patatine e bibita',
        'price' => '5,50',
        'image' => 'https://meydan-kebap.com/wp-content/uploads/2021/04/menu_falafel.png',
    ],
    [
        'type' => 'Poke',
        'name' => 'Poke Bowl',
        'ingredients' => 'Ingredienti misti',
        'description' => '“Poke” (si legge “poh-kay”) è una parola che in hawaiano significa “tagliare a pezzi”. Effettivamente, questo nome si riferisce a un piatto base della cucina hawaiana che è diventato quasi un simbolo nazionale, conosciuto e apprezzato da tutti coloro che visitano le isole dell’arcipelago. Consiste molto semplicemente in pesce crudo o carne tagliati a cubetti, conditi e accompagnati da altri ingredienti freschi.',
        'price' => '10,90',
        'image' => 'https://www.fattoincasadabenedetta.it/wp-content/uploads/2022/05/Poke-Bowl-Vegano-IG-1-1010x1024.jpg',
    ],
];
